// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: login.proto

#include "login.pb.h"
#include "login.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* LoginService_method_names[] = {
  "/LoginService/Login",
};

std::unique_ptr< LoginService::Stub> LoginService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LoginService::Stub> stub(new LoginService::Stub(channel));
  return stub;
}

LoginService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Login_(LoginService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LoginService::Stub::Login(::grpc::ClientContext* context, const ::UserDetails& request, ::Token* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Login_, context, request, response);
}

void LoginService::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::UserDetails* request, ::Token* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::Token>* LoginService::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::UserDetails& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::Token>::Create(channel_.get(), cq, rpcmethod_Login_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Token>* LoginService::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::UserDetails& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::Token>::Create(channel_.get(), cq, rpcmethod_Login_, context, request, false);
}

LoginService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoginService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoginService::Service, ::UserDetails, ::Token>(
          std::mem_fn(&LoginService::Service::Login), this)));
}

LoginService::Service::~Service() {
}

::grpc::Status LoginService::Service::Login(::grpc::ServerContext* context, const ::UserDetails* request, ::Token* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


